name: CI

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Fetch geo data
        run: npm run fetchExternal

      - name: Build index
        run: npm run buildIndex

      - id: getRepoBasename
        uses: actions/github-script@0.9.0
        with:
          script: |
            return context.repo.repo
          result-encoding: string

      - name: Build and push Docker images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{steps.getRepoBasename.outputs.result}}
          tag_with_ref: true
          tag_with_sha: true
